### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by Geczy** [j4k0xb/webcrack#18]
### Describe the bug

`webcrack ~/index.js`

### Expected Behaviour

work

### Code

```JavaScript
https://gist.github.com/Geczy/a274e77ebd2969ed0e2e4d53c2730ef6
```

### Logs

```Text
matt@pc:~$ webcrack ~/index.js
  webcrack:transforms prepare: started +0ms
  webcrack:transforms prepare: finished with 13930 changes +4s
  webcrack:transforms deobfuscate: started +0ms
  webcrack:deobfuscate String Array: 14034 strings +0ms
  webcrack:deobfuscate String Array Rotate: yes +3ms
  webcrack:deobfuscate String Array Encodings: 1 +40ms
  webcrack:transforms inlineObjectProps: started +3s
  webcrack:transforms inlineObjectProps: finished with 0 changes +735ms
  webcrack:transforms inlineDecoderWrappers: started +0ms
  webcrack:transforms inlineDecoderWrappers: finished with 86937 changes +4s
  webcrack:transforms inlineDecodedStrings: started +21ms
Segmentation fault
```

**Comment by j4k0xb** [comment]
Works on my machine™

But based on where it crashes it's likely caused by the native dependency https://github.com/laverdet/isolated-vm
What's your node version and OS?
- For node 20.x try if it works with `NODE_OPTIONS=no-node-snapshot webcrack ~/index.js`
- Otherwise try reinstalling webcrack (which will use the correct isolated-vm binary depending for your node version)

**Comment by Geczy** [comment]
yeah i was just using an old node version accidentally
