### ISSUE TITLE
How can I bundle the generated unpack files again?

### ISSUE THREAD

**Issue by cestsiva** [j4k0xb/webcrack#2]
i have a huge bundled js file, use this awesome tool i can get the unpack files, and do some rewrite in specific modules, after that, how can I bundle all the modules again.

Thanks a lot for your answer

**Comment by j4k0xb** [comment]
Currently, only the `deobfuscated.js` file is designed to behave the same as the original and the unpacker is for reverse-engineering.
But I definitely plan on allowing it to be bundled again.

For now you could try using any bundler like webpack, but there's a high chance it won't work yet...
Especially if it contains code like this which has to be changed first:
```js
require.r(exports);
require.d(exports, "AddEquation", function () {
  return M;
});
```
```js
var t = require("./118.js");
var i = require.n(t);
```

Another option would be to reuse the original bundle and replace the modules with the ones you edited.

**Comment by j4k0xb** [comment]
Status update:

I made the necessary changes and was able to run webpack on a huge unpacked bundle (6.3Mb, almost 400 cjs/esm modules) of a website and execute that instead of the original.
Everything seems to work and I could even see the individual modules in devtools and place breakpoints:
![image](https://user-images.githubusercontent.com/55899582/220158180-34bf5799-68b3-4a87-ac32-6251f3095e18.png)

Can you try it locally before I publish a new release?
```sh
git clone git@github.com:j4k0xb/webcrack.git
cd webcrack
npm run build
npm start -- yourBundle.js
```
After making the changes:
```sh
npx webpack-cli --mode development --output-path bundled ./webcrack-out
```

**Comment by cestsiva** [comment]
Great. it is exactly what i want.
after i try the steps you mentioned, i don't get the expected result. i put the file in here. https://minigame-1300810619.cos.ap-guangzhou.myqcloud.com/pageScript_lly.min.format.js. you can try.
maybe the script is somewhat a rare case.

**Comment by j4k0xb** [comment]
It was just a small edge case, fixed
